apiVersion: apps/v1
kind: Deployment
metadata:
  name: skattservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skattservice
  template:
    metadata:
      labels:
        app: skattservice
    spec:
      containers:
      - name: skattservice
        image: johannesdigdir/skatt_service:37ffb5c99ff59c8673ac89e794c4b2873d18b8ee
        ports:
        - containerPort: 5000